greeting: Hello

security:
  user:
    name: admin
    password: hellowrld!

management:
  security:
    role: ADMIN

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

endpoints:
  health:
    sensitive: false

spring:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
   io:
    pivotal:
      singapore: DEBUG

---

spring:
  profiles: spanish

greeting: Hola