greeting: Hello

security:
  user:
    name: admin
    password: hellowrld!

management:
  security:
    role: ADMIN

info:
  build:
    artifact: hello-spring-boot
    name: hello-spring-boot
    description: Demo project for Spring Boot
    version: 0.0.1-SNAPSHOT

endpoints:
  health:
    sensitive: false

---

spring:
  profiles: spanish

greeting: Hola